//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.common
{

public sealed partial class Effect :  Bright.Config.BeanBase 
{
    public Effect(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        Tag = (Enum.EffectTagType)_buf.ReadInt();
        Type = (Enum.EffectType)_buf.ReadInt();
        ModifierNumric = _buf.ReadFloat();
        ModifierType = (Enum.NumricModifierType)_buf.ReadInt();
        Take = (Enum.EffectTakeType)_buf.ReadInt();
        PostInit();
    }

    public static Effect DeserializeEffect(ByteBuf _buf)
    {
        return new common.Effect(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 携带的Tag类型，添加时添加tag，移除时，移除tag
    /// </summary>
    public Enum.EffectTagType Tag { get; private set; }
    /// <summary>
    /// Effect类型
    /// </summary>
    public Enum.EffectType Type { get; private set; }
    /// <summary>
    /// 修改器数值
    /// </summary>
    public float ModifierNumric { get; private set; }
    /// <summary>
    /// 数值修改器类型
    /// </summary>
    public Enum.NumricModifierType ModifierType { get; private set; }
    /// <summary>
    /// 生效时机
    /// </summary>
    public Enum.EffectTakeType Take { get; private set; }

    public const int __ID__ = -458280172;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "Tag:" + Tag + ","
        + "Type:" + Type + ","
        + "ModifierNumric:" + ModifierNumric + ","
        + "ModifierType:" + ModifierType + ","
        + "Take:" + Take + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
