//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Cfg.Common
{
   
public partial class Scripts
{
    private readonly Dictionary<int, Common.Table_Scripts> _dataMap;
    private readonly List<Common.Table_Scripts> _dataList;
    
    public Scripts(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Common.Table_Scripts>();
        _dataList = new List<Common.Table_Scripts>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Common.Table_Scripts _v;
            _v = Common.Table_Scripts.DeserializeTable_Scripts(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Common.Table_Scripts> DataMap => _dataMap;
    public List<Common.Table_Scripts> DataList => _dataList;

    public Common.Table_Scripts GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Common.Table_Scripts Get(int key) => _dataMap[key];
    public Common.Table_Scripts this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}