//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.Common
{

public sealed partial class Table_SoundEffectMap :  Bright.Config.BeanBase 
{
    public Table_SoundEffectMap(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        asset_path = _buf.ReadString();
        desc = _buf.ReadString();
        PostInit();
    }

    public static Table_SoundEffectMap DeserializeTable_SoundEffectMap(ByteBuf _buf)
    {
        return new Common.Table_SoundEffectMap(_buf);
    }

    /// <summary>
    /// 音效ID
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 音效资源路径（Assets/Res 开始的完整路径）
    /// </summary>
    public string asset_path { get; private set; }
    /// <summary>
    /// 备注
    /// </summary>
    public string desc { get; private set; }

    public const int __ID__ = -586482032;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "asset_path:" + asset_path + ","
        + "desc:" + desc + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
