//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.Common
{

public sealed partial class Table_Effect :  Bright.Config.BeanBase 
{
    public Table_Effect(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        Type = (Enum.EffectType)_buf.ReadInt();
        ExtensionParam = Bean.EffectExtensionParam.DeserializeEffectExtensionParam(_buf);
        ModifierType = (Enum.NumricModifierType)_buf.ReadInt();
        EffectOnAwake = _buf.ReadBool();
        Policy = (Enum.DurationPolicy)_buf.ReadInt();
        Period = _buf.ReadFloat();
        Duration = _buf.ReadFloat();
        Target = _buf.ReadInt();
        EffectType = (Enum.Actor_Attr)_buf.ReadInt();
        {int n = System.Math.Min(_buf.ReadSize(), _buf.Size);DeriveEffects = new int[n];for(var i = 0 ; i < n ; i++) { int _e;_e = _buf.ReadInt(); DeriveEffects[i] = _e;}}
        {int n = System.Math.Min(_buf.ReadSize(), _buf.Size);AwakeEffects = new int[n];for(var i = 0 ; i < n ; i++) { int _e;_e = _buf.ReadInt(); AwakeEffects[i] = _e;}}
        PostInit();
    }

    public static Table_Effect DeserializeTable_Effect(ByteBuf _buf)
    {
        return new Common.Table_Effect(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// Effect的类型
    /// </summary>
    public Enum.EffectType Type { get; private set; }
    /// <summary>
    /// 额外参数float_1,float_2,float_3,float_4,int_1,int_2,int_3,int_4
    /// </summary>
    public Bean.EffectExtensionParam ExtensionParam { get; private set; }
    /// <summary>
    /// 数值修改器类型
    /// </summary>
    public Enum.NumricModifierType ModifierType { get; private set; }
    /// <summary>
    /// 施加后立刻生效
    /// </summary>
    public bool EffectOnAwake { get; private set; }
    /// <summary>
    /// 生效策略
    /// </summary>
    public Enum.DurationPolicy Policy { get; private set; }
    /// <summary>
    /// 生效周期，单位秒
    /// </summary>
    public float Period { get; private set; }
    /// <summary>
    /// 持续时间,单位秒
    /// </summary>
    public float Duration { get; private set; }
    /// <summary>
    /// 目标类型，0=我方，1=敌方
    /// </summary>
    public int Target { get; private set; }
    /// <summary>
    /// 影响的数值类型
    /// </summary>
    public Enum.Actor_Attr EffectType { get; private set; }
    /// <summary>
    /// 派生effect
    /// </summary>
    public int[] DeriveEffects { get; private set; }
    /// <summary>
    /// effect被唤起时派生一次的effect
    /// </summary>
    public int[] AwakeEffects { get; private set; }

    public const int __ID__ = 1812133477;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        ExtensionParam?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        ExtensionParam?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "Type:" + Type + ","
        + "ExtensionParam:" + ExtensionParam + ","
        + "ModifierType:" + ModifierType + ","
        + "EffectOnAwake:" + EffectOnAwake + ","
        + "Policy:" + Policy + ","
        + "Period:" + Period + ","
        + "Duration:" + Duration + ","
        + "Target:" + Target + ","
        + "EffectType:" + EffectType + ","
        + "DeriveEffects:" + Bright.Common.StringUtil.CollectionToString(DeriveEffects) + ","
        + "AwakeEffects:" + Bright.Common.StringUtil.CollectionToString(AwakeEffects) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
