//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.Common
{

public sealed partial class Table_Effect :  Bright.Config.BeanBase 
{
    public Table_Effect(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        Tag = (Enum.EffectTagType)_buf.ReadInt();
        Type = (Enum.EffectType)_buf.ReadInt();
        ExtensionParam = Struct.EffectExtensionParam.DeserializeEffectExtensionParam(_buf);
        ModifierType = (Enum.NumricModifierType)_buf.ReadInt();
        Take = (Enum.DurationPolicy)_buf.ReadInt();
        Period = _buf.ReadFloat();
        Target = _buf.ReadInt();
        EffectType = (Enum.Actor_Attr)_buf.ReadInt();
        {int n = System.Math.Min(_buf.ReadSize(), _buf.Size);DeriveEffects = new int[n];for(var i = 0 ; i < n ; i++) { int _e;_e = _buf.ReadInt(); DeriveEffects[i] = _e;}}
        PostInit();
    }

    public static Table_Effect DeserializeTable_Effect(ByteBuf _buf)
    {
        return new Common.Table_Effect(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 携带的Tag类型，添加时添加tag，移除时，移除tag
    /// </summary>
    public Enum.EffectTagType Tag { get; private set; }
    /// <summary>
    /// Effect的类型
    /// </summary>
    public Enum.EffectType Type { get; private set; }
    /// <summary>
    /// 额外参数（float,float,float,int,int,int）
    /// </summary>
    public Struct.EffectExtensionParam ExtensionParam { get; private set; }
    /// <summary>
    /// 数值修改器类型
    /// </summary>
    public Enum.NumricModifierType ModifierType { get; private set; }
    /// <summary>
    /// 生效策略
    /// </summary>
    public Enum.DurationPolicy Take { get; private set; }
    /// <summary>
    /// 生效周期，单位毫秒
    /// </summary>
    public float Period { get; private set; }
    /// <summary>
    /// 目标类型，0=我方，1=敌方
    /// </summary>
    public int Target { get; private set; }
    /// <summary>
    /// 影响的数值类型
    /// </summary>
    public Enum.Actor_Attr EffectType { get; private set; }
    /// <summary>
    /// 派生effect
    /// </summary>
    public int[] DeriveEffects { get; private set; }

    public const int __ID__ = 1812133477;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        ExtensionParam?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        ExtensionParam?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "Tag:" + Tag + ","
        + "Type:" + Type + ","
        + "ExtensionParam:" + ExtensionParam + ","
        + "ModifierType:" + ModifierType + ","
        + "Take:" + Take + ","
        + "Period:" + Period + ","
        + "Target:" + Target + ","
        + "EffectType:" + EffectType + ","
        + "DeriveEffects:" + Bright.Common.StringUtil.CollectionToString(DeriveEffects) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
