//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.Common
{

public sealed partial class Table_Scripts :  Bright.Config.BeanBase 
{
    public Table_Scripts(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        AssetPath = _buf.ReadString();
        Type = (Enum.Script_Type)_buf.ReadInt();
        PostInit();
    }

    public static Table_Scripts DeserializeTable_Scripts(ByteBuf _buf)
    {
        return new Common.Table_Scripts(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 脚本路径
    /// </summary>
    public string AssetPath { get; private set; }
    /// <summary>
    /// 注入脚本类型
    /// </summary>
    public Enum.Script_Type Type { get; private set; }

    public const int __ID__ = -192960844;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "AssetPath:" + AssetPath + ","
        + "Type:" + Type + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
