//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Cfg.common
{
   
public partial class TB_AbilityBase
{
    private readonly Dictionary<int, common.AbilityBase> _dataMap;
    private readonly List<common.AbilityBase> _dataList;
    
    public TB_AbilityBase(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, common.AbilityBase>();
        _dataList = new List<common.AbilityBase>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            common.AbilityBase _v;
            _v = common.AbilityBase.DeserializeAbilityBase(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
        PostInit();
    }

    public Dictionary<int, common.AbilityBase> DataMap => _dataMap;
    public List<common.AbilityBase> DataList => _dataList;

    public common.AbilityBase GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public common.AbilityBase Get(int key) => _dataMap[key];
    public common.AbilityBase this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}