//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.role
{

public sealed partial class RoleBaseAttr :  Bright.Config.BeanBase 
{
    public RoleBaseAttr(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Class = (Enum.Role_Class)_buf.ReadInt();
        TestBoolean = _buf.ReadBool();
        {int n = System.Math.Min(_buf.ReadSize(), _buf.Size);TestMap = new System.Collections.Generic.Dictionary<int, int>(n * 3 / 2);for(var i = 0 ; i < n ; i++) { int _k;  _k = _buf.ReadInt(); int _v;  _v = _buf.ReadInt();     TestMap.Add(_k, _v);}}
        TestVector = _buf.ReadUnityVector3();
        {int n = System.Math.Min(_buf.ReadSize(), _buf.Size);TestArr = new int[n];for(var i = 0 ; i < n ; i++) { int _e;_e = _buf.ReadInt(); TestArr[i] = _e;}}
        PostInit();
    }

    public static RoleBaseAttr DeserializeRoleBaseAttr(ByteBuf _buf)
    {
        return new role.RoleBaseAttr(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 职业
    /// </summary>
    public Enum.Role_Class Class { get; private set; }
    /// <summary>
    /// 测试布尔值
    /// </summary>
    public bool TestBoolean { get; private set; }
    /// <summary>
    /// 测试键值对
    /// </summary>
    public System.Collections.Generic.Dictionary<int, int> TestMap { get; private set; }
    /// <summary>
    /// 测试向量
    /// </summary>
    public UnityEngine.Vector3 TestVector { get; private set; }
    /// <summary>
    /// 测试数组或集合
    /// </summary>
    public int[] TestArr { get; private set; }

    public const int __ID__ = -876445296;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Class:" + Class + ","
        + "TestBoolean:" + TestBoolean + ","
        + "TestMap:" + Bright.Common.StringUtil.CollectionToString(TestMap) + ","
        + "TestVector:" + TestVector + ","
        + "TestArr:" + Bright.Common.StringUtil.CollectionToString(TestArr) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
