//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Cfg.Role
{
   
public partial class RoleMeta
{
    private readonly Dictionary<int, Role.Table_RoleMeta> _dataMap;
    private readonly List<Role.Table_RoleMeta> _dataList;
    
    public RoleMeta(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Role.Table_RoleMeta>();
        _dataList = new List<Role.Table_RoleMeta>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Role.Table_RoleMeta _v;
            _v = Role.Table_RoleMeta.DeserializeTable_RoleMeta(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Role.Table_RoleMeta> DataMap => _dataMap;
    public List<Role.Table_RoleMeta> DataList => _dataList;

    public Role.Table_RoleMeta GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Role.Table_RoleMeta Get(int key) => _dataMap[key];
    public Role.Table_RoleMeta this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}