//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Cfg.role
{
   
public partial class TB_RoleMeta
{
    private readonly Dictionary<int, role.RoleMeta> _dataMap;
    private readonly List<role.RoleMeta> _dataList;
    
    public TB_RoleMeta(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, role.RoleMeta>();
        _dataList = new List<role.RoleMeta>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            role.RoleMeta _v;
            _v = role.RoleMeta.DeserializeRoleMeta(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
        PostInit();
    }

    public Dictionary<int, role.RoleMeta> DataMap => _dataMap;
    public List<role.RoleMeta> DataList => _dataList;

    public role.RoleMeta GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public role.RoleMeta Get(int key) => _dataMap[key];
    public role.RoleMeta this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}