//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Cfg.role
{
   
public partial class TB_RoleBaseAttr
{
    private readonly Dictionary<int, role.RoleBaseAttr> _dataMap;
    private readonly List<role.RoleBaseAttr> _dataList;
    
    public TB_RoleBaseAttr(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, role.RoleBaseAttr>();
        _dataList = new List<role.RoleBaseAttr>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            role.RoleBaseAttr _v;
            _v = role.RoleBaseAttr.DeserializeRoleBaseAttr(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
        PostInit();
    }

    public Dictionary<int, role.RoleBaseAttr> DataMap => _dataMap;
    public List<role.RoleBaseAttr> DataList => _dataList;

    public role.RoleBaseAttr GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public role.RoleBaseAttr Get(int key) => _dataMap[key];
    public role.RoleBaseAttr this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}