//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// Ability选择器类型
    /// </summary>
    public enum AbilitySelectType
    {
        /// <summary>
        /// 单体目标选择
        /// </summary>
        Single = 1,
        /// <summary>
        /// 圆形范围选择
        /// </summary>
        Circle = 2,
        /// <summary>
        /// 地面点选择
        /// </summary>
        Point = 3,
        /// <summary>
        /// 施法方向选择
        /// </summary>
        Direction = 4,
        /// <summary>
        /// 直线范围选择
        /// </summary>
        Line = 5,
        /// <summary>
        /// 全图角色目标选择
        /// </summary>
        GlobalActor = 6,
        /// <summary>
        /// 显式候选角色目标选择
        /// </summary>
        SecondaryActor = 7,
    }
}
