//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// Ability选择器类型
    /// </summary>
    public enum AbilitySelectType
    {
        /// <summary>
        /// 单体目标选择
        /// </summary>
        Single = 1,
        /// <summary>
        /// 圆形范围选择
        /// </summary>
        Circle = 2,
    }
}
