//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// 角色基础属性类型枚举，索引RoleMeta表格
    /// </summary>
    public enum Actor_Base_Attr
    {
        /// <summary>
        /// 无效
        /// </summary>
        Invalid = -1,
        /// <summary>
        /// HP上限
        /// </summary>
        HP = 0,
        /// <summary>
        /// MP上限
        /// </summary>
        MP = 1,
        /// <summary>
        /// 基础攻击力系数
        /// </summary>
        ATK = 2,
        /// <summary>
        /// 基础防御力
        /// </summary>
        DEF = 3,
        /// <summary>
        /// 基础速度
        /// </summary>
        SPD = 4,
        /// <summary>
        /// 基础移动力
        /// </summary>
        MVT = 5,
        /// <summary>
        /// 力量
        /// </summary>
        STR = 6,
        /// <summary>
        /// 敏捷
        /// </summary>
        AGI = 7,
        /// <summary>
        /// 法力
        /// </summary>
        SPW = 8,
        /// <summary>
        /// 最大值
        /// </summary>
        Max = 9,
    }
}
