//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// 角色Tag类型枚举，描述角色状态
    /// </summary>
    public enum ActorTagType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = -1,
        /// <summary>
        /// 眩晕1
        /// </summary>
        Stun = 0,
        /// <summary>
        /// 无敌10
        /// </summary>
        God = 1,
        /// <summary>
        /// 中毒100
        /// </summary>
        Tox = 2,
        /// <summary>
        /// 施法中1000
        /// </summary>
        Casting = 3,
        /// <summary>
        /// 流血10000
        /// </summary>
        Blood = 4,
        /// <summary>
        /// 读条中100000
        /// </summary>
        WindUp = 5,
    }
}
