//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// 角色Tag类型枚举，描述角色状态
    /// </summary>
    [System.Flags]
    public enum ActorTagType
    {
        /// <summary>
        /// 眩晕1
        /// </summary>
        Stun = 1,
        /// <summary>
        /// 无敌10
        /// </summary>
        God = 2,
        /// <summary>
        /// 施法中100
        /// </summary>
        Casting = 4,
    }
}
