//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// Actor技能类子tag
    /// </summary>
    public enum ActorTagSubType_Status
    {
        /// <summary>
        /// 无
        /// </summary>
        None = -1,
        /// <summary>
        /// 战斗中
        /// </summary>
        Fighting = 0,
        /// <summary>
        /// 已死亡
        /// </summary>
        Dead = 1,
        /// <summary>
        /// 传送中
        /// </summary>
        Teleporting = 2,
    }
}
