//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// 角色属性类型枚举
    /// </summary>
    public enum Attribute_Type
    {
        /// <summary>
        /// 无效
        /// </summary>
        Invalid = 0,
        /// <summary>
        /// HP上限
        /// </summary>
        HP = 1,
        /// <summary>
        /// MP上限
        /// </summary>
        MP = 2,
        /// <summary>
        /// 基础攻击力系数
        /// </summary>
        ATK = 3,
        /// <summary>
        /// 基础防御力
        /// </summary>
        DEF = 4,
        /// <summary>
        /// 基础速度
        /// </summary>
        SPD = 5,
        /// <summary>
        /// 基础移动力
        /// </summary>
        MVT = 6,
        /// <summary>
        /// 力量
        /// </summary>
        STR = 7,
        /// <summary>
        /// 敏捷
        /// </summary>
        AGI = 8,
        /// <summary>
        /// 法力
        /// </summary>
        SPW = 9,
    }
}
