//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// cast request reject bit flags
    /// </summary>
    [System.Flags]
    public enum CastRejectFlags
    {
        /// <summary>
        /// accepted
        /// </summary>
        None = 0,
        /// <summary>
        /// cmd is null or malformed
        /// </summary>
        InvalidCmd = 1,
        /// <summary>
        /// castor id &lt;= 0
        /// </summary>
        InvalidCastorId = 2,
        /// <summary>
        /// ability id &lt;= 0
        /// </summary>
        InvalidAbilityId = 4,
        /// <summary>
        /// castor actor instance not found
        /// </summary>
        CastorNotFound = 8,
        /// <summary>
        /// target actor instance not found or target is not allowed empty
        /// </summary>
        TargetNotFound = 16,
        /// <summary>
        /// castor missing Addon_Ability
        /// </summary>
        MissingAbilityAddon = 32,
        /// <summary>
        /// ability spec missing on castor
        /// </summary>
        AbilitySpecMissing = 64,
        /// <summary>
        /// ability cooldown not ready
        /// </summary>
        CooldownNotReady = 128,
        /// <summary>
        /// ability cost not enough
        /// </summary>
        CostNotEnough = 256,
        /// <summary>
        /// target type not supported
        /// </summary>
        UnsupportedTargetType = 512,
    }
}
