//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// cast request reject primary code
    /// </summary>
    public enum CastRejectCode
    {
        /// <summary>
        /// accepted
        /// </summary>
        None = 0,
        /// <summary>
        /// cmd is null or malformed
        /// </summary>
        InvalidCmd = 1000,
        /// <summary>
        /// castor id &lt;= 0
        /// </summary>
        InvalidCastorId = 1001,
        /// <summary>
        /// ability id &lt;= 0
        /// </summary>
        InvalidAbilityId = 1002,
        /// <summary>
        /// castor actor instance not found
        /// </summary>
        CastorNotFound = 1003,
        /// <summary>
        /// target actor instance not found or target is not allowed empty
        /// </summary>
        TargetNotFound = 1004,
        /// <summary>
        /// castor missing Addon_Ability
        /// </summary>
        MissingAbilityAddon = 1100,
        /// <summary>
        /// ability spec missing on castor
        /// </summary>
        AbilitySpecMissing = 1101,
        /// <summary>
        /// ability cooldown not ready
        /// </summary>
        CooldownNotReady = 1200,
        /// <summary>
        /// ability cost not enough
        /// </summary>
        CostNotEnough = 1201,
        /// <summary>
        /// target type not supported
        /// </summary>
        UnsupportedTargetType = 1300,
        /// <summary>
        /// unknown reject reason
        /// </summary>
        Unknown = 9000,
    }
}
