//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// Effect生效策略
    /// </summary>
    public enum DurationPolicy
    {
        /// <summary>
        /// 立即
        /// </summary>
        Instant = 1,
        /// <summary>
        /// 周期
        /// </summary>
        Duration = 2,
        /// <summary>
        /// 永久
        /// </summary>
        Infinite = 3,
    }
}
