//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// Effect的类型
    /// </summary>
    public enum EffectType
    {
        /// <summary>
        /// 冷却类effect
        /// </summary>
        CoolDown = 1,
        /// <summary>
        /// 消耗类Effect
        /// </summary>
        Cost = 2,
        /// <summary>
        /// 物理伤害
        /// </summary>
        PhyDamage = 3,
        /// <summary>
        /// 召唤物
        /// </summary>
        Summon = 4,
        /// <summary>
        /// 周期性固定数值伤害
        /// </summary>
        PeriodFixedDamage = 5,
    }
}
