//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// Effect类型枚举
    /// </summary>
    public enum EffectTagType
    {
        /// <summary>
        /// 无效1
        /// </summary>
        Invalid = 1,
        /// <summary>
        /// CD类型枚举10
        /// </summary>
        CoolDown = 2,
        /// <summary>
        /// 消耗类型枚举，消耗某项数值100
        /// </summary>
        Cost = 4,
    }
}
