//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// 修改属性类型的effect检查条件
    /// </summary>
    public enum effect_mod_attr_condition
    {
        /// <summary>
        /// 百分比
        /// </summary>
        Percentage = 1,
        /// <summary>
        /// 固定数值
        /// </summary>
        FixedValue = 2,
    }
}
