//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// Effect影响的tag类型
    /// </summary>
    public enum EffectTagType
    {
        /// <summary>
        /// 无效0
        /// </summary>
        Invalid = 0,
        /// <summary>
        /// 消耗类型枚举，消耗某项数值1
        /// </summary>
        Cost = 1,
        /// <summary>
        /// 冷却10
        /// </summary>
        CoolDown = 2,
        /// <summary>
        /// 中毒
        /// </summary>
        Tox = 3,
    }
}
