//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// 角色数值枚举
    /// </summary>
    public enum Numric_Type
    {
        /// <summary>
        /// 当前生命
        /// </summary>
        Curr_HP = 0,
        /// <summary>
        /// 生命上限
        /// </summary>
        Max_HP = 1,
        /// <summary>
        /// 当前法力
        /// </summary>
        Curr_MP = 2,
        /// <summary>
        /// 法力上限
        /// </summary>
        Max_MP = 3,
        /// <summary>
        /// 攻击力
        /// </summary>
        ATK = 4,
        /// <summary>
        /// 防御力
        /// </summary>
        DEF = 5,
        /// <summary>
        /// 速度
        /// </summary>
        SPD = 6,
        /// <summary>
        /// 移动力
        /// </summary>
        MVT = 7,
        /// <summary>
        /// 力量
        /// </summary>
        STR = 8,
        /// <summary>
        /// 敏捷
        /// </summary>
        AGI = 9,
        /// <summary>
        /// 法力
        /// </summary>
        SPW = 10,
        /// <summary>
        /// 最大值，所有的新增属性都添加在它之前，不要超过此值
        /// </summary>
        Max = 11,
    }
}
