//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// 数值修改器类型
    /// </summary>
    public enum NumricModifierType
    {
        /// <summary>
        /// 加法
        /// </summary>
        Sum = 1,
        /// <summary>
        /// 乘法
        /// </summary>
        Mult = 2,
        /// <summary>
        /// 除法
        /// </summary>
        Dive = 3,
        /// <summary>
        /// 无
        /// </summary>
        None = 4,
    }
}
