//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// Resolve request source type / 结算请求来源类型
    /// </summary>
    public enum ResolveSourceType
    {
        /// <summary>
        /// Unknown or unspecified source / 未知或未指定的来源
        /// </summary>
        Unknown = 0,
        /// <summary>
        /// Triggered by combat pipeline / 由战斗管线触发
        /// </summary>
        PipelineTrigger = 1,
        /// <summary>
        /// Directly applied by effect / 由效果直接应用
        /// </summary>
        EffectDirect = 2,
        /// <summary>
        /// Poison damage type, damage over time / 毒性伤害类型，持续伤害
        /// </summary>
        PoisonDamage = 3,
        /// <summary>
        /// True damage that ignores armor / 真实伤害，无视护甲
        /// </summary>
        TrueDamage = 4,
    }
}
