//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// Resolve phase flow signal type / 结算阶段流程信号类型
    /// </summary>
    public enum ResolveFlowSignalType
    {
        /// <summary>
        /// Proceed to next phase / 继续执行下一阶段
        /// </summary>
        Continue = 0,
        /// <summary>
        /// Skip current phase and continue / 跳过当前阶段继续执行
        /// </summary>
        Skip = 1,
        /// <summary>
        /// Interrupt entire resolve process / 中断整个结算流程
        /// </summary>
        Interrupt = 2,
        /// <summary>
        /// Jump to a specific phase / 跳转到指定的结算阶段
        /// </summary>
        JumpTo = 3,
        /// <summary>
        /// Abort resolve process with reason / 中止结算流程并附带原因
        /// </summary>
        Abort = 4,
    }
}
