//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// Resolve phase execution policy (bit flags) / 结算阶段执行策略（位标志）
    /// </summary>
    [System.Flags]
    public enum ResolvePhasePolicy
    {
        /// <summary>
        /// No special policy, execute normally / 无特殊策略，正常执行
        /// </summary>
        None = 0,
        /// <summary>
        /// Skip this phase before execution / 执行前跳过此阶段
        /// </summary>
        Skip = 1,
        /// <summary>
        /// Interrupt pipeline before this phase executes / 在此阶段执行前中断管线
        /// </summary>
        InterruptBeforeExecute = 2,
    }
}
