//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// 角色类型
    /// </summary>
    public enum RoleType
    {
        /// <summary>
        /// 无效
        /// </summary>
        Invalid = 0,
        /// <summary>
        /// 英雄单位
        /// </summary>
        Hero = 1,
        /// <summary>
        /// 随从，AI单位
        /// </summary>
        Minion = 2,
        /// <summary>
        /// 法球
        /// </summary>
        Orb = 3,
        /// <summary>
        /// 子弹
        /// </summary>
        Bullet = 4,
    }
}
