//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// 角色职业
    /// </summary>
    public enum Role_Class
    {
        /// <summary>
        /// 战士
        /// </summary>
        Warior = 1,
        /// <summary>
        /// 术士
        /// </summary>
        Warlock = 2,
        /// <summary>
        /// 猎人
        /// </summary>
        Hunter = 3,
        /// <summary>
        /// 法师
        /// </summary>
        Mage = 4,
    }
}
