//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// 角色类型
    /// </summary>
    public enum RoleType
    {
        /// <summary>
        /// 我方可操作的角色单位
        /// </summary>
        Hero = 1,
        /// <summary>
        /// 随从，我方的AI单位
        /// </summary>
        Minion = 2,
    }
}
