//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfg.Enum
{
    /// <summary>
    /// 脚本周期类型
    /// </summary>
    public enum Script_Type
    {
        /// <summary>
        /// 只在开始启动一次，然后关闭
        /// </summary>
        On_Start = 1,
        /// <summary>
        /// 需要手动回调结束
        /// </summary>
        Start_End = 2,
    }
}
