using System.IO;
using System.Text;
using GameFramework;
using UnityEditor;
using UnityEngine;

//ReSharper disable once CheckNamespace
namespace Aquila.Editor
{
    /// <summary>
    /// 表ID枚举生成器
    /// </summary>
    public static class FormIdEnumGenerator
    {
        [MenuItem( "Aquila/GenFormIdEnum" )]
        public static void GenFormIdEnum()
        {
            var enumFilePath = Utility.Path.GetRegularPath(@"Assets/Script/UI/FormIdEnum.cs");
            if (!File.Exists(enumFilePath))
            {
                Debug.Log($"GenFormIdEnum.GenFormIdEnum_()--->!File.Exists(enumFilePath)");
                return;
            }
            
            StringBuilder generator = new StringBuilder();
            generator.AppendLine( "// generated by tool,do not modify" );
            generator.AppendLine( "namespace Aquila.UI" );
            generator.AppendLine( "{" );
            generator.AppendLine( "\tpublic enum FormIdEnum : uint " );
            generator.AppendLine( "\t{" );

            var fileName = @"Assets/Res/Config/UIForm.txt";
            var rows = File.ReadAllLines( fileName,Encoding.GetEncoding("GB2312") );
            var len = rows.Length;
            string row = string.Empty;
            string[] fields = null;
            for ( var i = 4; i < len; i++ )
            {
                row = rows[i];
                fields = row.Split( '\t' );
                var assetPath = fields[3];
                if ( string.IsNullOrEmpty( assetPath ) )
                {
                    Debug.LogWarning( $"<color=yellow>GenInternalTable.GenFormIdEnum()--->assetPath is null</color>" );
                    break;
                }
                //Assets / Res / UI / TestForm.prefab
                var comment = fields[2];
                var formName = Path.GetFileNameWithoutExtension( assetPath );
                generator.AppendLine( "\t\t/// <summary>" );
                generator.AppendLine( $"\t\t/// {comment}" );
                generator.AppendLine( "\t\t/// </summary>" );
                generator.AppendLine( $"\t\t{formName}," );
            }

            generator.AppendLine( "\t}" );
            generator.AppendLine( "}" );
            File.WriteAllText
                ( 
                    enumFilePath,
                    generator.ToString(),
                    System.Text.Encoding.UTF8
                );
            Debug.Log("<color=white>Generating compelete.</color>");
            AssetDatabase.Refresh();
        }
    }

}
