//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.Single
{

public sealed partial class Table_GameText :  Bright.Config.BeanBase 
{
    public Table_GameText(ByteBuf _buf) 
    {
        AbilityUsingResult_NoTarget_l10n_key = _buf.ReadString(); AbilityUsingResult_NoTarget = _buf.ReadString();
        AbilityUsingResult_NoCastor_l10n_key = _buf.ReadString(); AbilityUsingResult_NoCastor = _buf.ReadString();
        AbilityUsingResult_NotEnoughMana_l10n_key = _buf.ReadString(); AbilityUsingResult_NotEnoughMana = _buf.ReadString();
        AbilityUsingResult_NotReady_l10n_key = _buf.ReadString(); AbilityUsingResult_NotReady = _buf.ReadString();
        AbilityUsingResult_NoParam_l10n_key = _buf.ReadString(); AbilityUsingResult_NoParam = _buf.ReadString();
        AbilityUsingResult_NoMeta_l10n_key = _buf.ReadString(); AbilityUsingResult_NoMeta = _buf.ReadString();
        AbilityUsingResult_NoTimeline_l10n_key = _buf.ReadString(); AbilityUsingResult_NoTimeline = _buf.ReadString();
        PostInit();
    }

    public static Table_GameText DeserializeTable_GameText(ByteBuf _buf)
    {
        return new Single.Table_GameText(_buf);
    }

    public string AbilityUsingResult_NoTarget { get; private set; }
    public string AbilityUsingResult_NoTarget_l10n_key { get; }
    public string AbilityUsingResult_NoCastor { get; private set; }
    public string AbilityUsingResult_NoCastor_l10n_key { get; }
    public string AbilityUsingResult_NotEnoughMana { get; private set; }
    public string AbilityUsingResult_NotEnoughMana_l10n_key { get; }
    public string AbilityUsingResult_NotReady { get; private set; }
    public string AbilityUsingResult_NotReady_l10n_key { get; }
    public string AbilityUsingResult_NoParam { get; private set; }
    public string AbilityUsingResult_NoParam_l10n_key { get; }
    public string AbilityUsingResult_NoMeta { get; private set; }
    public string AbilityUsingResult_NoMeta_l10n_key { get; }
    public string AbilityUsingResult_NoTimeline { get; private set; }
    public string AbilityUsingResult_NoTimeline_l10n_key { get; }

    public const int __ID__ = -130935786;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        AbilityUsingResult_NoTarget = translator(AbilityUsingResult_NoTarget_l10n_key, AbilityUsingResult_NoTarget);
        AbilityUsingResult_NoCastor = translator(AbilityUsingResult_NoCastor_l10n_key, AbilityUsingResult_NoCastor);
        AbilityUsingResult_NotEnoughMana = translator(AbilityUsingResult_NotEnoughMana_l10n_key, AbilityUsingResult_NotEnoughMana);
        AbilityUsingResult_NotReady = translator(AbilityUsingResult_NotReady_l10n_key, AbilityUsingResult_NotReady);
        AbilityUsingResult_NoParam = translator(AbilityUsingResult_NoParam_l10n_key, AbilityUsingResult_NoParam);
        AbilityUsingResult_NoMeta = translator(AbilityUsingResult_NoMeta_l10n_key, AbilityUsingResult_NoMeta);
        AbilityUsingResult_NoTimeline = translator(AbilityUsingResult_NoTimeline_l10n_key, AbilityUsingResult_NoTimeline);
    }

    public override string ToString()
    {
        return "{ "
        + "AbilityUsingResult_NoTarget:" + AbilityUsingResult_NoTarget + ","
        + "AbilityUsingResult_NoCastor:" + AbilityUsingResult_NoCastor + ","
        + "AbilityUsingResult_NotEnoughMana:" + AbilityUsingResult_NotEnoughMana + ","
        + "AbilityUsingResult_NotReady:" + AbilityUsingResult_NotReady + ","
        + "AbilityUsingResult_NoParam:" + AbilityUsingResult_NoParam + ","
        + "AbilityUsingResult_NoMeta:" + AbilityUsingResult_NoMeta + ","
        + "AbilityUsingResult_NoTimeline:" + AbilityUsingResult_NoTimeline + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
