/// <summary>
/// generated by tool,do not modify
/// <summary>
namespace Aquial.UI
{
	public enum FormIdEnum : byte 
	{
		/// <summary>
		/// ���Խ���
		/// <summary>
		TestForm,
		/// <summary>
		/// ���ܽ���
		/// <summary>
		AbilityForm,
	}
}
