// generated by tool,do not modify
namespace Aquila.UI
{
	public enum FormIdEnum : uint 
	{
		/// <summary>
		/// 测试界面
		/// </summary>
		TestForm,
		/// <summary>
		/// 技能界面
		/// </summary>
		AbilityForm,
		/// <summary>
		/// WindUp界面
		/// </summary>
		WindUpForm,
		/// <summary>
		/// 技能测试界面
		/// </summary>
		AbilityEditorTestForm,
	}
}
