/// <summary>
/// generated by tool,do not modify
/// <summary>
namespace Aquial.UI
{
	public enum FormIdEnum : byte 
	{
		/// <summary>
		/// 测试界面
		/// <summary>
		TestForm,
		/// <summary>
		/// 技能界面
		/// <summary>
		AbilityForm,
		/// <summary>
		/// WindUp界面
		/// <summary>
		WindUpForm,
		/// <summary>
		/// 技能测试界面
		/// <summary>
		AbilityEditorTestForm,
	}
}
