//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;


namespace Cfg
{
   
public partial class Tables
{
    public item.TbItem TbItem {get; }
    public role.TB_RoleBaseAttr TB_RoleBaseAttr {get; }
    public single.TB_SceneConfig TB_SceneConfig {get; }
    public common.TB_Scripts TB_Scripts {get; }
    public role.TB_RoleMeta TB_RoleMeta {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbItem = new item.TbItem(loader("item_tbitem")); 
        tables.Add("item.TbItem", TbItem);
        TB_RoleBaseAttr = new role.TB_RoleBaseAttr(loader("role_tb_rolebaseattr")); 
        tables.Add("role.TB_RoleBaseAttr", TB_RoleBaseAttr);
        TB_SceneConfig = new single.TB_SceneConfig(loader("single_tb_sceneconfig")); 
        tables.Add("single.TB_SceneConfig", TB_SceneConfig);
        TB_Scripts = new common.TB_Scripts(loader("common_tb_scripts")); 
        tables.Add("common.TB_Scripts", TB_Scripts);
        TB_RoleMeta = new role.TB_RoleMeta(loader("role_tb_rolemeta")); 
        tables.Add("role.TB_RoleMeta", TB_RoleMeta);

        PostInit();
        TbItem.Resolve(tables); 
        TB_RoleBaseAttr.Resolve(tables); 
        TB_SceneConfig.Resolve(tables); 
        TB_Scripts.Resolve(tables); 
        TB_RoleMeta.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbItem.TranslateText(translator); 
        TB_RoleBaseAttr.TranslateText(translator); 
        TB_SceneConfig.TranslateText(translator); 
        TB_Scripts.TranslateText(translator); 
        TB_RoleMeta.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}