//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Cfg.Fight
{
   
public partial class AbilityTimeline
{
    private readonly Dictionary<int, Fight.Table_AbilityTimeline> _dataMap;
    private readonly List<Fight.Table_AbilityTimeline> _dataList;
    
    public AbilityTimeline(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Fight.Table_AbilityTimeline>();
        _dataList = new List<Fight.Table_AbilityTimeline>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Fight.Table_AbilityTimeline _v;
            _v = Fight.Table_AbilityTimeline.DeserializeTable_AbilityTimeline(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Fight.Table_AbilityTimeline> DataMap => _dataMap;
    public List<Fight.Table_AbilityTimeline> DataList => _dataList;

    public Fight.Table_AbilityTimeline GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Fight.Table_AbilityTimeline Get(int key) => _dataMap[key];
    public Fight.Table_AbilityTimeline this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}