//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Cfg.Fight
{
   
public partial class CombatPhase
{
    private readonly Dictionary<string, Fight.Table_CombatPhase> _dataMap;
    private readonly List<Fight.Table_CombatPhase> _dataList;
    
    public CombatPhase(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, Fight.Table_CombatPhase>();
        _dataList = new List<Fight.Table_CombatPhase>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Fight.Table_CombatPhase _v;
            _v = Fight.Table_CombatPhase.DeserializeTable_CombatPhase(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.phase_key, _v);
        }
        PostInit();
    }

    public Dictionary<string, Fight.Table_CombatPhase> DataMap => _dataMap;
    public List<Fight.Table_CombatPhase> DataList => _dataList;

    public Fight.Table_CombatPhase GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Fight.Table_CombatPhase Get(string key) => _dataMap[key];
    public Fight.Table_CombatPhase this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}