//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.Fight
{

public sealed partial class Table_CombatPhase :  Bright.Config.BeanBase 
{
    public Table_CombatPhase(ByteBuf _buf) 
    {
        profile_id = _buf.ReadInt();
        phase = _buf.ReadInt();
        phase_order = _buf.ReadInt();
        policy = _buf.ReadInt();
        comment = _buf.ReadString();
        phase_key = _buf.ReadString();
        PostInit();
    }

    public static Table_CombatPhase DeserializeTable_CombatPhase(ByteBuf _buf)
    {
        return new Fight.Table_CombatPhase(_buf);
    }

    /// <summary>
    /// 结算配置档位ID（1=默认，2=无视护甲）
    /// </summary>
    public int profile_id { get; private set; }
    /// <summary>
    /// 阶段枚举值（ResolvePhaseType: 0..10）
    /// </summary>
    public int phase { get; private set; }
    /// <summary>
    /// 同 profile 内阶段顺序，从1开始
    /// </summary>
    public int phase_order { get; private set; }
    /// <summary>
    /// 阶段策略位（ResolvePhasePolicy: None=0, Skip=1, InterruptBeforeExecute=2）
    /// </summary>
    public int policy { get; private set; }
    /// <summary>
    /// 备注
    /// </summary>
    public string comment { get; private set; }
    /// <summary>
    /// 组合主键（profile_id_phase）
    /// </summary>
    public string phase_key { get; private set; }

    public const int __ID__ = 1478348088;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "profile_id:" + profile_id + ","
        + "phase:" + phase + ","
        + "phase_order:" + phase_order + ","
        + "policy:" + policy + ","
        + "comment:" + comment + ","
        + "phase_key:" + phase_key + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
