//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.Fight
{

public sealed partial class Table_FormulaSlot :  Bright.Config.BeanBase 
{
    public Table_FormulaSlot(ByteBuf _buf) 
    {
        phase = _buf.ReadInt();
        pre_formula_id = _buf.ReadInt();
        main_formula_id = _buf.ReadInt();
        post_formula_id = _buf.ReadInt();
        comment = _buf.ReadString();
        PostInit();
    }

    public static Table_FormulaSlot DeserializeTable_FormulaSlot(ByteBuf _buf)
    {
        return new Fight.Table_FormulaSlot(_buf);
    }

    /// <summary>
    /// 阶段枚举值（ResolvePhaseType: 0..10）
    /// </summary>
    public int phase { get; private set; }
    /// <summary>
    /// 前置公式ID（未配置=-1）
    /// </summary>
    public int pre_formula_id { get; private set; }
    /// <summary>
    /// 主公式ID（未配置=-1）
    /// </summary>
    public int main_formula_id { get; private set; }
    /// <summary>
    /// 后置公式ID（未配置=-1）
    /// </summary>
    public int post_formula_id { get; private set; }
    /// <summary>
    /// 备注
    /// </summary>
    public string comment { get; private set; }

    public const int __ID__ = -2012543275;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "phase:" + phase + ","
        + "pre_formula_id:" + pre_formula_id + ","
        + "main_formula_id:" + main_formula_id + ","
        + "post_formula_id:" + post_formula_id + ","
        + "comment:" + comment + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
