//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.Fight
{

public sealed partial class Table_Formula :  Bright.Config.BeanBase 
{
    public Table_Formula(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        Expression = _buf.ReadString();
        PostInit();
    }

    public static Table_Formula DeserializeTable_Formula(ByteBuf _buf)
    {
        return new Fight.Table_Formula(_buf);
    }

    /// <summary>
    /// Formula ID / 公式ID
    /// </summary>
    public int id { get; private set; }
    public string Expression { get; private set; }

    public const int __ID__ = -1014326217;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "Expression:" + Expression + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
