//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.Fight
{

public sealed partial class Table_CombatPhase :  Bright.Config.BeanBase 
{
    public Table_CombatPhase(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        PhaseType = (Enum.ResolvePhaseType)_buf.ReadInt();
        FormulaId = _buf.ReadInt();
        PostInit();
    }

    public static Table_CombatPhase DeserializeTable_CombatPhase(ByteBuf _buf)
    {
        return new Fight.Table_CombatPhase(_buf);
    }

    /// <summary>
    /// Combat phase ID / 结算阶段ID
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// Resolve phase type enum / 结算阶段类型枚举，对应 Pipeline/PhaseHandler 中各阶段的处理逻辑
    /// </summary>
    public Enum.ResolvePhaseType PhaseType { get; private set; }
    /// <summary>
    /// Formula reference ID / 引用的公式ID
    /// </summary>
    public int FormulaId { get; private set; }

    public const int __ID__ = 1478348088;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "PhaseType:" + PhaseType + ","
        + "FormulaId:" + FormulaId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
