//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.Fight
{

public sealed partial class Table_CombatPhaseProvider :  Bright.Config.BeanBase 
{
    public Table_CombatPhaseProvider(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        {int n = System.Math.Min(_buf.ReadSize(), _buf.Size);PhaseIds = new int[n];for(var i = 0 ; i < n ; i++) { int _e;_e = _buf.ReadInt(); PhaseIds[i] = _e;}}
        PostInit();
    }

    public static Table_CombatPhaseProvider DeserializeTable_CombatPhaseProvider(ByteBuf _buf)
    {
        return new Fight.Table_CombatPhaseProvider(_buf);
    }

    /// <summary>
    /// Combat phase provider ID / 结算管线配置ID
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// Ordered list of CombatPhase IDs defining the resolve pipeline sequence / 结算阶段ID有序列表，定义结算管线的执行顺序
    /// </summary>
    public int[] PhaseIds { get; private set; }

    public const int __ID__ = -268992695;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "PhaseIds:" + Bright.Common.StringUtil.CollectionToString(PhaseIds) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
