//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.Fight
{

public sealed partial class Table_AbilityBaseInfo :  Bright.Config.BeanBase 
{
    public Table_AbilityBaseInfo(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        name = _buf.ReadString();
        AbilityID = _buf.ReadInt();
        TimelineID = _buf.ReadInt();
        Desc = _buf.ReadString();
        PostInit();
    }

    public static Table_AbilityBaseInfo DeserializeTable_AbilityBaseInfo(ByteBuf _buf)
    {
        return new Fight.Table_AbilityBaseInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string name { get; private set; }
    /// <summary>
    /// 技能ID
    /// </summary>
    public int AbilityID { get; private set; }
    /// <summary>
    /// TimelineID
    /// </summary>
    public int TimelineID { get; private set; }
    /// <summary>
    /// 技能描述
    /// </summary>
    public string Desc { get; private set; }

    public const int __ID__ = -1354741702;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "AbilityID:" + AbilityID + ","
        + "TimelineID:" + TimelineID + ","
        + "Desc:" + Desc + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
